### PR TITLE
Rohan Issue F1 + B2: Frontend for AnnouncementForm/Table and Backend CRUD Operations for Announcement Endpoints

### LINKED ISSUE #14: Issue F1: fixtures/components for announcements
Developer Story:

As an developer

- I have access to fixtures, components and storybook stories for a form and table for Announcements
- So that I can build future features for the Announcements table

Acceptance Criteria:

- [ ]  There is a form component for announcements suitable for crud operations (similar to team03 form components, but with a nice large textarea for the announcement text.) Note that the commonsId is not part of the form; it will be set implicitly.
- [ ]  There is a table component for announcements (similar to team03 table components) Note that the commonsId is not part of the table component; it will be the same for all entries in the table, so we will put it at the top of the page separately.
- [ ]  There are fixtures that match the format of the GET operations for the API endpoints being worked on in the second issue. Note that the fixtures should be organized so that each set of announcements is for a single commons, since we only ever work with the announcements for one commons at at time, even though in the database they are all stored in the same database able.
- [ ]  There are storybook entries for the form and table components. Note that the storybook entries for the table should focus on one commons at a time (see discussion above under fixtures).

### PR DESCRIPTION
**Pull request by rohankumar2025**
In this PR, we implement the Frontend components, stories, and tests for AnnouncementForm and AnnouncementTable. We also add fixtures for Announcements. (edit: Because of backend problems, the backend entity, repository, controller and tests are also implemented in this PR)

Hosted at: https://hc-rk-dev.dokku-02.cs.ucsb.edu/

Storybook:
Screenshot 2024-03-03 at 4 04 11 PM
Screenshot 2024-03-03 at 4 04 33 PM

Closes #14 and #13

### CODE REVIEW

**Review by ahjsuy — DISMISSED** [review]
LGTM

**Comment by rohankumar2025** [comment]
Dev hosting:

https://happy-cows-rohankumar-dev.dokku-02.cs.ucsb.edu/

**Review by BK1031 — DISMISSED** [review]
lgtm

**Comment by rohankumar2025** [comment]
New Dev hosting at: https://hc-rk-dev.dokku-02.cs.ucsb.edu/

All endpoints on Swagger should be working and frontend is still as shown on screenshots.

**Review by rkirsur — DISMISSED** [review]
lgtm

**Comment by ahjsuy** [comment]
I don't think my email is included in the admin emails to check it out on the dokku deployment.

**Review by sangitakunapuli — CHANGES_REQUESTED** [review]
remove package lock from your files changed!

**Comment by rohankumar2025** [comment]
> remove package lock from your files changed!

Fixed

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Pull request merged**
