### PR TITLE
Hide Chat in Play Page if showChat is false

### LINKED ISSUE #25: Make UI Respect showChat Field
In the UI, the chat button should be hidden for regular users if showChat is false.

### PR DESCRIPTION
**Pull request by KylebKumar**
## Overview
Hides the chat button in the play page for users if the showChat field is false.

## Screenshots (Optional)

Visible:
Screenshot 2024-03-03 at 5 45 54 PM

Hidden:
Screenshot 2024-03-03 at 5 46 58 PM

## Validation (Optional)
Performed manual testing and wrote unit tests. May need to perform manual testing again once it is actually possible to change the showChat field.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #25

### CODE REVIEW

**Review by ahjsuy — DISMISSED** [review]
LGTM

**Review by rkirsur — APPROVED** [review]
lgtm

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Comment by KylebKumar** [comment]
Code is deployed at: http://hc-kyle-dev.dokku-02.cs.ucsb.edu

**Review by rohankumar2025 — APPROVED** [review]
LGTM

**Pull request merged**
