### PR TITLE
Rohan Issue B2: CRUD Operations for Announcement Endpoints

### LINKED ISSUE #13: Issue B2: Backend Controller for CRUD operations for announcements
Developer Story:

As an developer

- I have access to backend endpoints (through swagger) for CRUD operations for the Announcements table
- So that I can build future features using this table

Acceptance Criteria:

- [x]  There is a POST endpoint to create new announcements
- [x]  The POST endpoint to create new announcements rejects POST values with invalid data (e.g. a commonsId for a commons that doesn't exist, announcements with empty text, end date that is before start date, start date blank)
- [x]  The POST endpoint allows end date to be blank, in which case it is stored as NULL in the database
- [x]  There is a GET endpoint to get all announcements for a specified commons
- [x]  There is a GET endpoint to get an announcement by its individual id number
- [x]  There is a PUT endpoint that allows updating the announcement. It performs the same validations as the POST endpoing.
- [x]  There is a DELETE endpoint that allows deleting an announcement

### PR DESCRIPTION
**Pull request by rohankumar2025**
In this PR, we implement CRUD operations for the Announcement endpoints and the tests to go along with it.

Hosted at: https://hc-rk-dev.dokku-02.cs.ucsb.edu/

Closes #13

### CODE REVIEW

**Review by KylebKumar — APPROVED** [review]
LGTM

**Comment by rohankumar2025** [comment]
Dev-hosting to showcase backend CRUD operations:

https://happy-cows-rohankumar-dev.dokku-02.cs.ucsb.edu/swagger-ui/index.html#/Announcements

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Comment by sangitakunapuli** [comment]
when attempting to test the deployment, I got a 403 Forbidden response on Swagger. can you confirm that you've tested these endpoints extensively on dokku?

**Review by rkirsur — APPROVED** [review]
lgtm

**Comment by rohankumar2025** [comment]
Changes in this PR will be reflected in the Rohan Issue F1 PR.

**Pull request closed without merging**
