### PR TITLE
Make API Endpoints Respect showChat field

### LINKED ISSUE #20: Make Backend Respect showChat Field
A PR to make the backend endpoints respect the value of the field, meaning they will respond for regular users if/only if the showChat field is true, and return 403 if the field is false, but admins get responses no matter what the value of the field is. You won't be able to test interactively, but you can write unit tests that will manually set up a commons where showChat is false for purposes of the unit test. Again, at this point, no users facing functionality has changed, since there is no interactive way to set the chat field either through the backend or the frontend.

### PR DESCRIPTION
**Pull request by KylebKumar**
## Overview
Added checks to the API such that regular users can only call backend Chat endpoints if the showChat property is true. Admins bypass these checks and can always call backend Chat endpoints. 

## Validation (Optional)
Performed manual testing and wrote unit tests to make sure all endpoints work when showChat is true, and no endpoints work for users when showChat is false.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #20

### CODE REVIEW

**Review by rohankumar2025 — DISMISSED** [review]
LGTM

**Review by sangitakunapuli — APPROVED** [review]
LGTM - please have a teammate do another review since the previous went stale

**Review by BK1031 — APPROVED** [review]
lgtm

**Comment by KylebKumar** [comment]
Code is deployed at: https://hc-kyle-dev.dokku-02.cs.ucsb.edu

**Pull request merged**
