### PR TITLE
Added showChat boolean to Commons entity

### LINKED ISSUE #11: Add showChat field to Commons entity
This issue is based off of the following step in the EPIC issue "Admin can turn off chat":

A PR that adds the fields to the entity with a default value of true (this preserves existing functionality, since at first it's just an extra field in the table, hanging out with a default value of true, that isn't being looked at in the code anywhere else. Make sure that creating a new commons or editing an existing one still works.)

### PR DESCRIPTION
**Pull request by KylebKumar**
## Overview

In this PR, we add the showChat field to the Commons entity. This field is currently set to true by default when a new commons is created, and is used nowhere in the code.

NOTE: This PR will break all existing data by putting it into a bad state where it has an empty show_chat property.

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #11

### CODE REVIEW

**Review by ahjsuy — APPROVED** [review]
LGTM once the lint test runs

**Review by rkirsur — APPROVED** [review]
lgtm

**Review by sangitakunapuli — CHANGES_REQUESTED** [review]
Please provide the deployment link for this change to ensure it doesn't change existing functionality.

**Comment by KylebKumar** [comment]
The code is deployed here: https://hc-kyle-dev.dokku-02.cs.ucsb.edu, and the create and edit functionality seems to work there

**Review by sangitakunapuli — APPROVED** [review]
LGTM

**Pull request merged**
